- README.md
There was an extra '\' sign in the docker pull command
> Removed extra '\' sign

- cmd/common.go
- cmd/util.go
- cmd/util_test.go
> Use kubectl to check the kubernetes version

- check/data
- check/test_test.go
- cmd/common.go
- cmd/util.go
- cmd/util_test.go
> Multiple words

- cfg/node.yaml
Kubelet option --streaming-connection-idle-timeout expects a string
value which fails parsing to integer for greater than comparison.
The string "0" indicates no timeout and this is what we are checking
for.
> Change node check 2.1.6 to use operation `noteq` instead of `gt`.

- cfg/config.yaml
- cfg/master.yaml
- cfg/node.yaml
- check/check.go
- cmd/common.go
- cmd/root.go
- cmd/util.go
- cmd/util_test.go
In this PR I've restructured the YAML. Each component has a set of possible binaries and config files, and we look through them to see which one is in use on the system. We then substitute the binaries and config file names into the tests. 
This means we don't need the --installation flag any more. If we learn about other executables or config file locations we can simply add them to the config.yaml file.
> Auto-detect executables and config files 

- cmd/common.go
- cmd/util.go
- cmd/util_test.go
#53 verifyKubeVersion is responsible for the error message. It's functionality has been superseded by getKubeVersion which is uses version information to load appropriate check definition file.
This PR delete calls to verifyKubeVersion and it's support functions.
> Client server error message on 1.6

- README.md
We support multiple versions of the CIS benchmark
> Remove reference to specific benchmark version

- cfg/1.8/federated.yaml
- cfg/1.8/master.yaml
Some of the remediation action output looked wrong because line breaks appeared in the middle of command line arguments. While I was at it I removed some extraneous spaces before full stops.
> Remove odd spacing and line breaks from test config files

- entrypoint.sh
The entrypoint.sh had a typo where it tried coping files from "/kube-bench" instead of just "/".
> Fixed typo in entrypoint.sh

- cfg/1.6/master.yaml
- cfg/1.7/master.yaml
- cfg/1.8/master.yaml
This issue affects master checks 1.4.11 and 1.4.12 in #88
> Fix etcd tests fail because kube-bench expects flags to be set with equal sign

- cfg/1.8/master.yaml
- If data-dir is not the last argument, the remaining arguments
are captured preventing the correct checking.
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>
> Improve etcd data directory extraction

- cmd/common.go
- cmd/root.go
Adds in the `--config-dir` and `--version` flags, allowing a user to specify the config directory containing benchmarks, and the target Kubernetes version, respectively.
> Allow kubernetes version and config directory to be specified (resolves #107)

- README.md
Since we are using go-releaser that's a perfectly good way to get the binaries
> Add link to releases page

- .travis.yml
Checks that cfg directory and kube-bench directories are in place on the host after running the install command from within a container
> Adding a test install to travis job

- entrypoint.sh
This sets `-e` to exit early if any line in the entrypoint script fails. Should help catch installation issues once Travis tests are set up for the Docker images (#120).
> Fail fast in container entrypoint

- cfg/1.8/node.yaml
The audit field in 2.2.6 item of 1.8/node.yaml is missing
> Addition of missing audit field in 2.2.6 node item

- cfg/1.8/master.yaml
check 1.4.11 and 1.4.22 shows FAIL even when permissions is correct.
> fix grep string for check 1.4.11 and 1.4.12

- cfg/1.8/config.yaml
Adds support for kops & kubespray configs that use the .manifest extension instead of .yaml
> Inlcude .manifest extension config files for kops & kubespray

- README.md
- cmd/root.go
Thought it would be useful to add a link to the CIS security kubernetes benchmark in the README. Also, corrected the link in the long description of the command. Hope this is useful!
> Add link to CIS kubernetes benchmark

- cfg/1.11/config.yaml
- cfg/1.11/node.yaml
- cmd/common.go
- cmd/util.go
- cmd/util_test.go
This PR fixes an issue with the current implementation which check only the kubelet config file for both kubelet config checks (2.2.1 and 2.2.2) and kubelet service file (2.2.3 and 2.2.4) which causes wrong results.
> Fix issue with kubelet config and unitfile checks

- cfg/1.11/node.yaml
Path to kubelet configuration was accidentally prefixed with a dollar
symbol (probably as a result of copying some other test that used
variable name).
After removing the dollar sign from paths both checks pass on conforming
deployment.
> Fixing checks 2.2.9 and 2.2.10 on 1.11 nodes.

- cfg/1.11/master.yaml
With multiple test items operator defaults to "and". In case of 1.3.7
the tests check whether --address flag is either set to 127.0.0.1 or not
set at all. Those conditions cannot be met at the same time.
> Fixing 1.3.7 on 1.11 master.

- README.md
Signed-off-by: Johannes M. Scheuermann <joh.scheuer@gmail.com>
In the latest Kubernetes releases the node label for the master node has changed from: `"kubernetes.io/role": "master"` to `"node-role.kubernetes.io/master": ""`. This PR corrects the `labelSelector` of the `kubectl run ..`command to work on clusters that are bootstrapped with `kubeadm`.
> Correct readme for 1.11 example

- cfg/1.11/master.yaml
Check 1.1.37 should pass if --features-gate is not set or if features-gate is set to AdvancedAuditing=false.
> Fix check 1.1.37.

- cfg/1.11/node.yaml
By default --make-iptables-util-chain is true, so PASS if this flag is not set.
> Fix node check 2.1.8

- README.md
I don't see how kube-bench can check the permissions on files unless it has access to them on the host, so I think we need to be mounting the /etc directory from the host. 
@ttousai can you double-check this please?
> read config files from host /etc

- README.md
Once the master node recommended check:
1.1.12 Ensure that the admission control plugin DenyEscalatingExec is set
has been followed, it is no longer possible to run kube-bench itself using kubectl.
> Document limitation of running with kubectl

- cfg/1.11/master.yaml
Added another test item that checks whether --disable-admission-plugins is not set and an "or" bin_op. 
This causes check 1.1.14 to be successful when the flag is not set, while still failing when the flag is set and includes the value NamespaceLifecycle
Fixes #192
> Changed 1.1.14 to not fail when flag is not set

- cmd/common.go
Only get runningVersion in [`runChecks()`](https://github.com/aquasecurity/kube-bench/blob/master/cmd/common.go#L47) if kubeVersion has not already been provided.
This should fix #176 
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>
> Only get runningVersion if --version has not been provided

- check/check.go
- check/check_test.go
- check/controls.go
- cmd/common.go
Support new check type - skip:
If a check is marked with type "skip", it will be marked as Info.
Support scored property:
If a check is not scored and is not marked with type skip, it will be marked as Warn.
> Type skip and not scored checks

- cmd/util.go
Made all the warnings to be logged and not printed, so when using the json flag the output will be only in json format.
fix #217
> Bugfix: Logging warning instead of printing

- cmd/util.go
Kube-bench doesn't scan the host when kubelet is not in path. We encountered with this issue on different PKS, GKE and AKS platforms.
One way to get the kubernetes version is by getting the kubelet path from the running process using ps
`ps -eo cmd | grep kubelet | awk '{print $1}' | grep kubelet` --version
And another way to get the kubernetes version is by finding the kubelet binary on the file system using find command
"`find / -type f -executable -name kubelet 2>/dev/null | grep -m1 .` --version"
I chose the second way (searching the fs) because it looks to me less risky then the first way (using ps).
> search for the kubelet binary when it is not in the path

- cfg/1.11/node.yaml
- cfg/1.8/node.yaml
Fix for #194 (which it turns out can affect many of the 2.1.* tests, not just 2.1.4)
Using the -C flag on ps should return only the processes with that command name, rather than any process that happens to have something with any argument that happens to match. 
@ttousai please could you try this out and see if you agree? 
I've only done this for the last two sets of config files since I doubt anyone is seriously using config files for Kubernetes 1.6 or 1.7 at this point (we could consider retiring those, but that's a separate matter).
> Only find flags on the process we really want

- cfg/1.11/node.yaml
- cfg/1.8/config.yaml
- cfg/1.8/node.yaml
- cfg/config.yaml
- cmd/common.go
- cmd/util.go
This is a more detailed solution to the issue reported in the PR #208. It fixes issues with variable substitutions for node benchmarks.
There are 3 major config files for kubelets k8s nodes:
- /etc/kubernetes/kubelet.conf ($kubeletkubeconfig)
- /var/lib/kubelet.config.yaml ($kubeletconf)
- /etc/systemd/system/kubelet.service.d/10-kubeadm.conf ($kubeletsvc)
In the previous versions of kube-bench there was no distinction between these files and results of running node checks were misleading. This PR adds the distinction and also adds support for a new type of variable `kubeconfig`.
> Fix issues with checks for kubelet configuration files

- cfg/ocp-3.10/config.yaml
- cfg/ocp-3.10/master.yaml
The OCP benchmarks uses configs only names of OCP component binaries. 
OCP configuration file paths are hardcoded into the benchmarks so there is no need to specify them in the `cfg/ocp-3.10/config.yaml` at the moment.
This commit cleans up the OCP config by removing all configurations except those component binaries required to run kube-bench on OCP installations and adding missing ones.
> Clean up OCP benchmark config.

- .gitignore
- Gopkg.lock
- README.md
- cmd/common.go
- cmd/root.go
- cmd/util.go
- cmd/util_test.go
- hack/debug.yaml
- hack/kind.yaml
- job.yaml
- makefile
This adds master node detection and a root command that automatically detect checks to run.
The root command will run node checks and if possible master checks. You can still override checks config files for master and node using respectively `--master-file` and `--node-file`.
The `master` and `node` commands are still supported for backward compatibility.
I've also added some Makefile targets to improve local testing and reflected changes into the documentation.
Closes https://github.com/aquasecurity/kube-bench/issues/72
> Adds master node detection 

- check/check.go
- check/data
- check/test.go
- check/test_test.go
Adds enhancement #241. This is useful for checking values in YAML (possibly JSON) kubernetes config files.
> Add ":" as a valid flag-value separator for tests

- cfg/1.11/master.yaml
Change test_items in 1.11 master.yaml check 1.5.2 to fix issue with check failing even when --client-cert-auth is set, mentioned in #270.
> Fix failing check 1.5.2 in version 1.11

- .gitignore
- Gopkg.lock
- Gopkg.toml
- check/check.go
- check/check_test.go
- check/controls.go
- check/controls_test.go
- cmd/common.go
- cmd/common_test.go
- cmd/root.go
- cmd/util.go
Changes:
1. Partially resolves #172 by adding support for `--scored` and `--unscored` flags
2. Some refactoring to facilitate unit testing of new/existing functionality.
Tested with unit tests and as well as minikube v1.0.0
> Add flags to further filter CIS checks to run

- check/check.go
Fixes: https://github.com/aquasecurity/kube-bench/issues/278
remediation field is missing in the json result and the actual remediation text shows up in test_info field.
After the fix:
```
./kube-bench master --version 1.13 --json -c 1.1.1 | jq .
{
"id": "1",
"version": "1.13",
"text": "Master Node Security Configuration",
"node_type": "master",
"tests": [
{
"section": "1.1",
"pass": 0,
"fail": 0,
"warn": 0,
"info": 0,
"desc": "API Server",
"results": [
{
"test_number": "1.1.1",
"test_desc": "Ensure that the --anonymous-auth argument is set to false (Not Scored)",
"type": "",
"remediation": "Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml\non the master node and set the below parameter.\n--anonymous-auth=false\n",
"test_info": null,
"status": …
```
> Fixing remediation field for json result

- cfg/1.11-json/config.yaml
- cfg/1.11/config.yaml
- cfg/1.13/config.yaml
- cfg/1.13/master.yaml
- cfg/1.8/config.yaml
- cfg/config.yaml
* Move some default values for kubelet and proxy into `cfg/config.yaml` so they don't have to be defined in version-specific files
* #193 fixed the file for 1.11 but not 1.13 - now fixed
> Config improvements

- check/check.go
- check/test.go
The expected result of each test, is generated from the test arguments from the yaml file.
Every expected result is a combination of expressions, separated by the binary operand (or/and).
Every expression is combined from the test item attributes:
flag, set and if there is - compare operand and compare value.
Example:
tests:
bin_op: or
test_items:
- flag: "--cgroup-parent"
set: false
- flag: "--cgroup-parent"
compare:
op: nothave
value: "/docker"
set: true
Expected result will be shown as: '--cgroup-parent' Is not present OR '--cgroup-parent' Not have '/docker'
Another example:
tests:
test_items:
- flag: "userns"
compare:
op: has
value: "userns"
set: true
Expected result will be shown as: 'userns' Has 'userns'
> Genereate expected result automatically for each test

- README.md
Values in the version-specific files override the main file.
I think this is the last outstanding item to-do for #235
> Document version-specific config files

- cfg/ocp-3.10/node.yaml
- check/controls_test.go
This improves the TestControls_RunChecks() test by making
more comprehensive assertions on a more fully fledged input yaml
Fixes: https://github.com/aquasecurity/kube-bench/issues/304
Signed-off-by: Simarpreet Singh <simar@linux.com>
> ocp-3.10: Fix malformed yaml and improve TestControls_RunChecks

- cmd/version.go
- makefile
This commit adds a version subcommand to display the kube-bench release version
Usage:
```
$ kube-bench version
V0.0.27
```
Addresses: https://github.com/aquasecurity/kube-bench/issues/311
Signed-off-by: Simarpreet Singh <simar@linux.com>
> kube-bench: add version subcommand

- go.mod
Due to go mod pointing to`	github.com/aquasecurity/kube-bench v0.0.29	` at line#6, it does not honor the current code and points to the dependency cache.
> fix go.mod dependency

- cmd/root.go
- cmd/util.go
```kube-bench master  --logtostderr=false   -v 9```
```cat /tmp/kube-bench.INFO
Log file created at: 2019/06/28 00:01:03
Running on machine: kubemaster1
Binary: Built with gc go1.11.11 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
```
It does not log anything else after that. 
After the fix we can see the output being recorded to the file: 
```cat /tmp/kube-bench.INFO
Log file created at: 2019/06/28 00:02:27
Running on machine: kubemaster1
Binary: Built with gc go1.12 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0628 00:02:27.340695 3203197 util.go:122] Looking for config for version 1.13
I0628 00:02:27.340919 3203197 util.go:127] Looking for config file: cfg/1.13/master.yaml
I0628 00:02:27.340960 3203197 …
```
> add glog flush to write the output to a file

- README.md
Without passing in kubeconfig credentials:
```bash
$ docker run --pid=host -v /etc:/etc:ro -v /var:/var:ro -v $(which kubectl):/usr/bin/kubectl -t lizrice/kube-bench:5e6cdfd master -v 1
I0628 16:52:06.591683    6099 util.go:367] Unable to get Kubernetes version from kubectl, using default version: 1.6
I0628 16:52:06.591822    6099 common.go:74] Using benchmark file: cfg/1.6/master.yaml
...
```
As updated in the README with this fix:
```bash
docker run --pid=host -v /etc:/etc:ro -v /var:/var:ro -v $(which kubectl):/usr/bin/kubectl -v ~/.kube:/.kube -e KUBECONFIG=/.kube/config -t lizrice/kube-bench:5e6cdfd master -v 1
I0628 16:53:26.784122    7224 util.go:131] No test file found for 1.14 - using tests for Kubernetes 1.13
I0628 16:53:26.784961    7224 common.go:228] Using config file: …
```
> Need credentials in order to run kubectl version

- .goreleaser.yml
This change should fix the Travis build error while **goreleaser** fails to build due to missing dependencies.
> turns Go Module on

- cfg/1.13-json/node.yaml
Adds `bin_op` to fix bugs on tests 2.1.4 and 2.1.5 - 1.13-json
> Fixes bugs on tests 2.1.4 and 2.1.5 - 1.13-json

- cfg/1.11/master.yaml
- cfg/1.13/master.yaml
#374 : The default for --enable-admission-plugins does not include AlwaysAdmit, changed this check to also pass if the flag isn't set.
> Updated check to pass if flag isn't set

- cfg/1.13/master.yaml
- cfg/1.13/node.yaml
test 1.1.12 got DEPRECATED.
test 1.1.34 changed to --encryption-provider-config and need to be set manually
> fixes-according-kube-cis1.4.1

- cfg/1.11/node.yaml
- cfg/1.13/node.yaml
according to [issue 347](https://github.com/aquasecurity/kube-bench/issues/347) ive been allowing the default streaming-connection-idle-timeout for both 1.11 and 1.13
> Correction to 1.13 and 1.13-json test 2.1.5

- cfg/1.6/node.yaml
Fix #291 
Replace the `gt` with `eq` for string comparison of kube-bench check 2.1.6 in `cfg/1.6/node.yaml`.
> Fix error converting from string to integer

- README.md
- cmd/root.go
Fixes #152
Set kubernetes version to the value of the environment variable `KUBE_BENCH_VERSION` if it is defined and the flag `--version` is not specified on the kube-bench command line.
The command line flag `--version` takes precedence of the environment variable `KUBE_BENCH_VERSION` if both are defined.
> Read kubernetes version from environment

- cfg/1.11/node.yaml
- cfg/1.13/node.yaml
- cfg/config.yaml
- job-iks.yaml
Fixes issue #386 
In the new `job-iks.yaml` file, the only difference is it's mapping `/lib/systemd` to `/etc/systemd`
> fixes issue #386

- cfg/config.yaml
This is another fix that's needed for issue #386 
hyperkube v1.15 renamed "proxy" to "kube-proxy"
> hyperkube v1.15 renamed "proxy" to "kube-proxy"

- cfg/1.13-json/node.yaml
The update is from the new cis version 1.4.1.
like asked in https://github.com/aquasecurity/kube-bench/issues/370
and already been done in the 1.13 
https://github.com/aquasecurity/kube-bench/pull/376
> update the yaml according cis kube benchmark  1.4.1

- README.md
We're now potentially looking at config files for which you might need to be root to even see. This can result in errors like:
`error looking for file /var/lib/kubelet/config.yaml: stat /var/lib/kubelet/config.yaml: permission denied`
If you're running as a container you effectively get this anyway so I don't think it's unreasonable to run as root, though we could consider an issue to warn (but carry on) when this happens.
> docs: note that you may need to be root

- cfg/config.yaml
This PR will make checking for the proxy binary optional.
Addresses: https://github.com/aquasecurity/kube-bench/issues/335 
Signed-off-by: Simarpreet Singh <simar@linux.com>
> cfg: Make proxy checks optional

- makefile
Updates the logic for `kind-push` in the makefile to use
the new, simple command provided by kind.
Fixes #458
> Use newer `kind load docker-image` command

- cmd/common.go
- cmd/common_test.go
- cmd/util.go
- cmd/util_test.go
Fixes Issue #331.
- When **kubectl** and **kubelet** are missing, the following error is displayed:
``` 
Version check failed:  
Unable to find the programs kubectl or kubelet in the PATH.
These programs are used to determine version of kubernetes.
Make sure the /usr/bin directory is mapped to the container,
either using the job.yaml file used, or docker command.
For job.yaml:
...
- name: usr-bin
mountPath: /usr/bin
...
For docker command:
docker -v $(which kubectl):/usr/bin/kubectl ....
Alternatively, you can specify the version with --version
kube-bench --version <VERSION> ...
- When component programs are missing, the following error is displayed:
```
Unable to find control plane programs (apiserver, controllermanager, etc...)
These program names are provided in the config.yaml, …
> Fixes Issue #331: Changes the Error Message When Programs are Missing  

- cmd/common.go
- cmd/common_test.go
- cmd/kubernetes_version.go
- cmd/kubernetes_version_test.go
- cmd/util.go
Fixes issue #517 
Determines Kubernetes version using the [REST API](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#without-using-a-proxy)
> Fixes issue #517: Determines Kubernetes version using the REST API

- .travis.yml
Fixes issue #391: 
Replaced calling docker directly by using "make build-docker"
> Fixes issue #391: Replaced calling docker directly by using "make build-docker"

- hooks/build
Adds kube-bench version to docker build hook. Ref: #522
> Adds kube-bench version to docker build hook

- cmd/common.go
- cmd/master.go
- cmd/node.go
- cmd/root.go
- cmd/run.go
- cmd/run_test.go
- cmd/util.go
- cmd/util_test.go
Adds `run` subcommand to partially cover what is discussed [here](https://github.com/aquasecurity/kube-bench/issues/494#issuecomment-559183325)
This works with the existing config files as follows:
* `kube-bench run` is equivalent to `kube-bench`
* `kube-bench run --sections master,node` is also equivalent to `kube-bench` 
* `kube-bench run --sections master` is equivalent to `kube-bench master`
* `kube-bench run --sections node` is equivalent to `kube-bench node`
I think that when we have new section files for CIS 1.5 we will be able to run, for example `kube-bench run --sections etcd` to run the tests in the etcd file. However, there will need to be settings in the `config.yaml` file(s) to cover `etcd` (just as we currently need settings for `master` and `node`. 
This PR does not …
> Add run subcommand 

- cfg/cis-1.5/master.yaml
Resolved bug in **master.yml** for **cis-1.5** for the **$apiserverbin** variable name in check **1.2.21**
For check **1.2.21**, a wrong variable name is referenced **$apiserver** which actually should be **$apiserverbin**
This was making check to fail even if the **profiling** argument is set to **false** for **apiserver**
Also resolved remediation description which din't list all the required **tls-cipher-suites** which are actually checked in the check **1.2.35**
> FIX : Resolved bug in related to apiserverbin variable name in check 1.2.21

- cfg/cis-1.3/master.yaml
- cfg/cis-1.3/node.yaml
- cfg/cis-1.4/master.yaml
- cfg/cis-1.4/node.yaml
- cfg/cis-1.5/master.yaml
- cfg/cis-1.5/node.yaml
- cfg/rh-0.7/master.yaml
- cfg/rh-0.7/node.yaml
Fixes #541 
Additionally the format of all file permissions checks was streamlined. Some of the config files had the order of the keys different, now the order is the same for all configs.
> added 444, 440, 400 and 000 file permission checks for all benchmarks

- job-eks.yaml
- job-iks.yaml
- job-master.yaml
- job-node.yaml
- job.yaml
By setting all host-mounted volumes to be read-only we reduce the likelihood
any host filesystem is modified by running kube-bench. This is a defense in depth measure that improves confidence in running kube-bench in production environments as well as allowing kube-bench to run where restrictive pod security policies are enforced.
> Set all host-mounted volumes to be read-only.

- Dockerfile
- README.md
- cmd/util.go
- hack/debug.yaml
- hack/kind.yaml
- integration/testdata/job-master.data
- integration/testdata/job.data
- job-master.yaml
- job-node.yaml
- job.yaml
And change to use `/usr/local/mount-from-host/bin` as mount path.
Fixes #574
> Fixes issue #574: change the PATH in container

- README.md
Correct misleading comment about anticipated CIS benchmarks for every Kubernetes release - bad assumption!
> docs: CIS benchmarks are not frequent

- CONTRIBUTING.md
We're now following the normal behaviour of glog, which means specifying --logtostderr to get the output written to screen. See https://godoc.org/github.com/golang/glog
> docs: update params for logging to screen

- README.md
Looks like this project now uses Go modules so `dep` steps are not needed.
> Removed references to `dep` from README.md

- README.md
This PR updates the `aws ecr get-login` command which is outdated.
> Update `Running in an EKS cluster` documentation

- cfg/cis-1.3/node.yaml
- cfg/cis-1.4/node.yaml
- cfg/cis-1.5/node.yaml
- cfg/gke-1.0/node.yaml
Fixed the common misspelling of "identied" instead of "identified" in the remediation instructions for CIS and GKE benchmark nodes.
- cfg/cis-1.3/node.yaml
- cfg/cis-1.4/node.yaml 
- cfg/cis-1.5/node.yaml
- cfg/gke-1.0/node.yaml
> Fix misspelling - identied / identified in remediation section of node.yaml

- .goreleaser.yml
This creates binaries for arm/amd64 that would show up on a release, so users could pull the binary and drop it into a container.
Partially fixes https://github.com/aquasecurity/kube-bench/issues/627
> .goreleaser: Create binaries for arm/arm64

- cmd/common.go
- cmd/common_test.go
- cmd/master.go
- cmd/node.go
- cmd/root.go
- cmd/run.go
- cmd/testdata/controlsCollection.json
- cmd/testdata/result.json
- integration/testdata/cis-1.5/job.data
Fixes #622 and fixes #603
New JSON output example:
```
[
{"id": "1", "text": "Master Node Security Configuration", ...},
{"id": "2", "text": "Etcd Node Configuration", ...},
{"id": "3", "text": "Control Plane Configuration", ...},
...
]
```
> Fix invalid JSON output

- cfg/cis-1.3/node.yaml
- cfg/cis-1.4/node.yaml
- cfg/cis-1.5/node.yaml
Fixes #642 by making the test posix compliant.
> make the kubelet cafile test posix compliant

- .travis.yml
- README.md
- cmd/common.go
- cmd/common_test.go
Hello!
We've been using kube-bench for quite a while in our CI pipeline for our EKS clusters. Up until the release of the eks benchmark, we had been using the vanilla 1.17 benchmark.
Following AWS's announcement of the new EKS-specific benchmark, I set out to try it out and switch to it. However I encountered errors while doing that.
The supported targets for the EKS benchmark weren't matching the documentation, or the config files for the benchmark.
```
kube-bench --benchmark eks-1.0 run --targets managedservice
The specified --targets "managedservice" does not apply to the CIS Benchmark eks-1.0 \n Valid targets [
```
This PR fixes the supported targets for EKS benchmark:
* Before that, `eks-1.0` was supposed to be supporting node, policies and managedservices. However using policies or …
> Fix supported targets for EKS benchmark

- check/check.go
- check/check_test.go
- check/controls_test.go
- check/data
- check/test.go
- check/test_test.go
> Support multiple values flag when check the audit output

- cmd/common.go
- cmd/master.go
- cmd/node.go
- cmd/root.go
- cmd/util.go
See #655. This outputs a warning if kubectl doesn't have access to kubeconfig and can't autodetect the version. 
Modified code to only run `getBenchmarkVersion()` once per command, so that this new warning doesn't get emitted four times! (Note that the `loadConfig()` function can get called several times from the code in root.go) 
This PR doesn't update the default version yet so it's not a full fix for the issue.
> Warn if kubectl can't autodetect the version 

- .travis.yml
- cmd/util.go
Remove Continue with error function
> Refactor: remove ContinueWithError

- .github/ISSUE_TEMPLATE/config.yml
- cfg/cis-1.5/node.yaml
- check/check.go
- check/check_test.go
- check/data
- check/test.go
- check/test_test.go
- integration/testdata/cis-1.5/job-node.data
- integration/testdata/cis-1.5/job.data
Fixes #646
This is a bit of a saga:
* Settings made on the command line override settings in a Kubernetes config file
* Audit commands are run to detect command line and other "external" settings; AuditConfig commands are used to get a configuration file in JSON or YAML format
* In the case of 4.2.4 the read-only-port setting defaults to 0 if it's set in the config file, so the test should pass if any of the following are true: --read-only-port is set to 0 on the command line; --read-only-port is not set on the command line and readOnlyPort is set to 0 in the config file; readOnlyPort is not set on either the command line or the config file.
To make this work I have refactored the way that a set of tests in a Check are run. Previously they ran all testItems in the check as Audit commands, …
> Better handling of parameters and config audits

- makefile
The `kind get kubeconfig-path` command no longer works.  Update makefile to create kube-bench local kubeconfig and use that.
Fixes #684
> Update makefile to create kubeconfig

- cfg/rh-0.7/master.yaml
- id: 4.6
text: "Verify the scheduler pod specification file ownership set by OpenShift"
audit: "stat -c %u:%g /etc/origin/node/pods/controller.yaml" -- (lower case u and g ) it returns the uID and gID in numeric i.e 0:0 not root:root.
it supposed to be Uppercase: audit: "stat -c %U:%G /etc/origin/node/pods/controller.yaml"
> Updating section id 4.6

- cfg/eks-1.0/node.yaml
- cfg/gke-1.0/node.yaml
Fixes a minor typo in proxy kubeconfig checks
> Fix remediation typo in 3.1.1 and 4.1.1

- CONTRIBUTING.md
- README.md
- cmd/root.go
Closes #695 
before:
```
$ ./kube-bench 
failed to get a set of executables needed for tests: unable to detect running programs for component "kubelet"
$ ./kube-bench --logtostderr
W0907 22:30:01.566933   17118 util.go:96] 
Unable to detect running programs for component "apiserver"
The following "master node" programs have been searched, but none of them have been found:
- kube-apiserver
- hyperkube apiserver
- hyperkube kube-apiserver
- apiserver
...
```
after:
```
$ ./kube-bench 
W0907 22:28:23.580054   16389 util.go:96] 
Unable to detect running programs for component "apiserver"
The following "master node" programs have been searched, but none of them have been found:
- kube-apiserver
- hyperkube apiserver
- hyperkube kube-apiserver
- apiserver
...
$ ./kube-bench --logtostderr=false …
```
> Default log output to stderr

- .travis.yml
- Dockerfile
- makefile
Addresses #671 by building a multi-arch image for arm64 as well as amd64
Also tidied up the makefile a bit, including: 
- removed duplicate run of unit tests
- added some dependencies for kind-run tests to make sure it's using an up-to-date image
Note that in the Dockerfile for some reason `go install` created an executable with a different name (not `kube-bench`) on amd64. I've worked around this by using `go build` instead.
> Multi-arch build 

- README.md
- Add note about why we don't support OCP 4.*
- Move GKE & OpenShift sub-sections next to EKS and AKS
- Minor corrections
> Note about OpenShift OCP 4.*

- check/test.go
actual Result is used later on to get actual value and the --include-test-output values but it never got set so its always empty.
> Set actualResult

- .travis.yml
- Dockerfile
Currently when PR from a fork its fails travis build because of security issues with the environment variables.
Used the changes made in https://github.com/aquasecurity/kube-bench/pull/706 
and just updated the travis file.
> Test Travis build condition

- cmd/common.go
Regrading https://github.com/aquasecurity/kube-bench/issues/701 where kube bench is crushing when not finding components
> Not exiting when executable not found

- README.md
Updated README with section on manually downloading and installing kube-bench on Linux.
Few other small documentation fixes.
Should help in closing #624
> Updated documentation with section on downloading and installing kube-bench

- cfg/cis-1.5/master.yaml
- cfg/cis-1.6/master.yaml
**Why do we need it?**
According to CIS Benchmark, item 1.2.35 allows kube-apiserver to configure with a subset of the given cipher suites. 
```
Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml
on the master node and set the below parameter as follows, or to a subset of these values.
```
However, using the current configuration, it checks whether this whole set is the same set or is a subset of the cipher suites configured in the kube-apiserver which violates the description. This PR changes `has` op to `valid_elements` to correct the check logic.
> Fix tls-cipher-suites check for kube-apiserver

- check/check.go
- check/controls.go
- check/controls_test.go
This fixes issue #649 allowing groups to be defined to be skipped. this is done by setting 'Skip' on the group to true. When checks are run this will then set the state of any checks within that group to info (the check is still technically run but just overridden to be INFO as I wasn't sure on what the desired behaviour here was, we could just skip the check entirely and not run and just set it to INFO).
Please let me know if there are any additional changes you want done to this!
> Allow for skip to be defined on a group-level skipping all checks inside

- cfg/config.yaml
**Why do we need it?**
This PR aims at fixing the bug reported in https://github.com/aquasecurity/kube-bench/pull/756.
**How to reproduce this bug?**
The `defaultkubeconfig` for scheduler and controllermanager don't take effect as they are mistakenly configured as an array.
When no files can be found in the declared `kubeconfig` location options. The substitution should fall back to replacing the variables with the default values, however, as the object type is mismatched, so there's no replacement to take place.
```
scheduler:
kubeconfig:
- /etc/kubernetes/scheduler.conf
defaultkubeconfig: /etc/kubernetes/scheduler.conf
```
The issue is initially introduced in https://github.com/aquasecurity/kube-bench/pull/738.
> Fix defaultkubeconfig in config.yaml to resolve variable exposure in remediation

- check/controls.go
- check/controls_test.go
- cmd/common.go
- cmd/common_test.go
- cmd/root.go
This adds the feature specified in the PR #564 
Currently this is how the workflow works:
- User can add --skip followed by any number of IDS 
- For each id before running checks it will see if it belongs to the current group or check.
- If it belongs to the current group all child checks are skipped, if it belongs to the current check only that current check is skipped.
- If skip is specified in the yaml or the command line parameter it will be skipped.
Although the original PR did have a comment specifying that 1.2.* for example could be good I wasn't sure if that was wanted so if any maintainer could let me know what they think of the current implementation and I can go from there, thanks!
> Allow for groups and checks to be skipped via command line parameter

- cmd/common.go
- cmd/common_test.go
- cmd/root.go
- cmd/testdata/passedControlsCollection.json
This is a change that addresses the issue #723
**Behaviour:**
- If exit-code parameter is unset it defaults to 0, meaning regardless of pass or failure it always returns exit code 0. (Assuming kube-bench made it to the end of execution without error)
- If exit-code is specified and is non-zero then if any control collection has more than 0 failures it will exit with the supplied exit code.
Please let me know if any additional changes are needed or if there is any change in functionality needed. I've tested locally and it all seems to work correctly.
> Add exit-code parameter for when checks have failed

- cfg/cis-1.5/controlplane.yaml
- cfg/cis-1.6/controlplane.yaml
- cfg/config.yaml
- integration/testdata/cis-1.5/job.data
**Why do we need it?**
This PR automates the verification of `3.2.1. Ensuring a minimal audit policy is created` by validating `--audit-policy-file` is set to kube-apiserver start command.
If this option is configured, the kube-apiserver will check the validity of the policy file during startup.
Quote from [Auditing](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy):
> Note that the rules field must be provided in the audit policy file. A policy with no (0) rules is treated as illegal.
So it's safe to mark the item as PASS as long as it is set.
> Automate check 3.2.1 Ensure that a minimal audit policy is created

- README.md
The command you listed here did not work. The command from the official documentation did:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html
`aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`
Thanks!
> Fix AWS ECR authentication docs

- cfg/cis-1.6/master.yaml
Currently, 1.2.1 has automated checks but in results it always warns. So without a manual type, it will fail or pass automatically.
> Automate 1.2.1

- cfg/cis-1.6/master.yaml
- cfg/config.yaml
In KOPS used etc-manager which bootstrap 2 etcd clusters: main (`/etc/kubernetes/manifests/etcd-main.manifest`) and event (`/etc/kubernetes/manifests/etcd-events.manifest`). So i changed logic and it check all manifests which contain etcd in naming in `/etc/kubernetes/manifests`.
Signed-off-by: Dmytro Oboznyi <dmytro.oboznyi@syncier.com>
> Fix 1.1.7 1.1.8 for KOPS

- cfg/config.yaml
**Summary**
Issue #808 
This PR update kube-bench configs to support Bottlerocket OS scanning.
These were my results:
**Before applying the changes requested**
```
== Summary node ==
1 checks PASS
13 checks FAIL
1 checks WARN
0 checks INFO
== Summary total ==
1 checks PASS
13 checks FAIL
1 checks WARN
0 checks INFO
```
**After applying the changes requested**
```
== Summary node ==
12 checks PASS
2 checks FAIL
1 checks WARN
0 checks INFO
== Summary total ==
12 checks PASS
2 checks FAIL
1 checks WARN
0 checks INFO
```
**After building a new Bottlerocket AMI that fixes those failed items reported by kube-bench**
```
== Summary node ==
14 checks PASS
0 checks FAIL
1 checks WARN
0 checks INFO
== Summary total ==
14 checks PASS
0 checks FAIL
1 checks WARN
0 checks INFO
```
Thanks for …
> Improve: Allow kube-bench to scan Bottlerocket OS

- .goreleaser.yml
The main config.yaml is missing at the tar.gz and debian packages.
Signed-off-by: Thorsten Schifferdecker <ts@systs.org>
> (fix) add config.yaml to releases, see #811

- README.md
Example commands should use auto-detection or the new `run --targets` approach to specifying sections of the benchmark to run
> docs: remove deprecated subcommands master / node

- cmd/common_test.go
- cmd/run.go
`defer` executes at function return, not out of block scope, so we should wrap `for` block by function.
> chore: fix defer func in for-loop

- README.md
It may be supposed to be a link.
> chore: fix an invalid markdown syntax

- cmd/common_test.go
- cmd/util.go
In some cases kube-bench will crush instead of fallback to default version. 
Fix it to only log that couldn't auto-detect version and used default.
> Fix fallback to default version

- cfg/cis-1.6/master.yaml
- cfg/cis-1.6/node.yaml
- cfg/config.yaml
- job-master.yaml
- job-node.yaml
- job.yaml
Running Kube-bench in kops clusters provide a lot of false-positive alerts, so such automation allows kube-bench search files and test them in addition to the list of known places in the config file. 
Signed-off-by: Dmytro Oboznyi <dmytro.oboznyi@syncier.com>
Ref #634
> Fix file permissions false positive

- job-master.yaml
> mount /etc/passwd and /etc/group for etcd ownership related checks

- cfg/cis-1.6/master.yaml
This PR covers the issue documented in #867 whereby CIS 1.1.9 ( and also 1.1.10 ) throw a WARNing for `/var/lib/cni/networks` in terms of permissions ( `chown` and `chmod` ), even though the same command, when run locally on the K8s nodes does not return an error.
#867 describes the issue in more detail but, in short, we see: -
```text
I0504 17:36:02.705809   21516 check.go:110] -----   Running check 1.1.9   -----
I0504 17:36:02.712997   21516 check.go:299] Command: "ps -ef | grep kubelet | grep -- --cni-conf-dir | sed 's%.*cni-conf-dir[= ]\\([^ ]*\\).*%\\1%' | xargs -I{} find {} -mindepth 1 | xargs stat -c permissions=%a\nfind /var/lib/cni/networks -type f | xargs --no-run-if-empty stat -c permissions=%a"
I0504 17:36:02.713018   21516 check.go:300] Output: …
```
> Issue 867: Fixing "No such file or directory" issue seen with CIS 1.1.9 and 1.1.0

- cfg/rh-0.7/master.yaml
Got few false positive alerts on a kube-bench report due to some typos.
> False positive when running rh-0.7 benchmarks

- go.mod
- go.sum
Update the go module files to go version 1.16 (we already updated the image) 
Issue #904
> Update go modules 1.16

- check/controls.go
ASFF string size need to be constraint, could explain https://github.com/aquasecurity/kube-bench/issues/903
`Message:Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Text should NOT be longer than 512 characters.
Error Code:InvalidInput`
> Check string size

- cfg/cis-1.20/master.yaml
An erroneous xargs statement resulting in an empty response when running the audit command.
> cis-1.20 section 1.1.10 command revision.

- cfg/gke-1.0/node.yaml
- job-gke.yaml
GKE benchmarks were returning several false-positives and failing tests that GKE has equivalent controls for.
Issue: #802 
1. GKE nodes' kubelet config file may be found at `/home/kubernetes/kubelet-config.yaml`. Modified the GKE kubernetes job to mount `/home/kubernetes` so that this file can be found. Also updated the volume mounts to be read only.
2. The CIS 4.1.9 check would fail for appropriate permissions if they were not exactly `644`. Changed the operation from `eq` to `bitmask` to resolve.
3. Skipped the failing checks that Google provides equivalent controls for (4.2.4, 4.2.6, 4.2.9, 4.2.10). See https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks#default-values for the justifications for these checks.
> GKE: Fix 4.1.9, skip irremediable checks, add /home/kubernetes mount

- cfg/config.yaml
In kubespray tool we have another path for kubelet config, add them to kube-bench config on top
Issue: #948
> Add node kubelet config path

- Dockerfile
Mitigating [CVE-2021-3711](https://nvd.nist.gov/vuln/detail/CVE-2021-3711) and [CVE-2021-3712](https://nvd.nist.gov/vuln/detail/CVE-2021-3712) issues with `openssl` in Alpine Linux 3.14
Fixes #980 
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>
> Update/upgrade Alpine before installing openssl

- cfg/cis-1.20/master.yaml
- cfg/cis-1.6/master.yaml
This transplants #687 to cis-1.6 and cis-1.20. Fixes #686 for cis-1.6 and cis-1.20.
> Add a trailing slash to find directory path

- cmd/master.go
- cmd/node.go
- cmd/root.go
- cmd/run.go
Fixes https://github.com/aquasecurity/kube-bench/issues/1000
> Fix the `--exit-code` flag doesn't work when run with subcommand

- check/controls.go
> ASFF: no longer include timestamp in the finding ID

- job-master.yaml
This is an attempt to fix issue described in #1250 -- however I'm not 100% on the approach, I would assume that you want backwards compatibility for K8s 1.23.x and below. Please advise about approach and I can make relevant amendments.
> Update job-master.yaml for K8s 1.24.x labels/tolerations (#1250)

- CONTRIBUTING.md
- cfg/config.yaml
- cfg/eks-stig-kubernetes-v1r6/config.yaml
- cfg/eks-stig-kubernetes-v1r6/controlplane.yaml
- cfg/eks-stig-kubernetes-v1r6/managedservices.yaml
- cfg/eks-stig-kubernetes-v1r6/master.yaml
- cfg/eks-stig-kubernetes-v1r6/node.yaml
- cfg/eks-stig-kubernetes-v1r6/policies.yaml
- docs/architecture.md
- docs/platforms.md
- docs/running.md
- hack/kind-stig.test.yaml
- hack/kind-stig.yaml
- integration/testdata/Expected_output_stig.data
- job-eks-stig.yaml
- makefile
> Adding eks-stig-kubernetes-v1r6

- cfg/cis-1.20/master.yaml
- cfg/cis-1.23/master.yaml
- cfg/cis-1.5/master.yaml
- cfg/cis-1.6/master.yaml
- cfg/config.yaml
- cmd/common.go
- cmd/util.go
- cmd/util_test.go
Use this way to support cases:
* The etcd server startup with no `--data-dir` flag,  it will use default value(`${name}.etcd`) as data-dir
* The value of `--data-dir`  flag is a relative path. Closes #583
refer:
* https://etcd.io/docs/v3.5/op-guide/configuration/#command-line-flags
> support customize datadir locations of etcd

- cfg/cis-1.6-k3s/etcd.yaml
- cfg/cis-1.6-k3s/master.yaml
fixed https://github.com/aquasecurity/kube-bench/issues/1351
This PR attempts to address sortcomings in several of the etcd and master config checks for CIS-1.6-K3s. 
- Most of these fixes revolve around one thing: `grep` returns a nonzero return code when it doesn't find anything. This is a problem for these K3s checks, as the whole point of the check is that the K3s config "is not setting this flag". To sidestep this issue, the grep results are piped to `cat` which does not care if the result is empty. This allows the `set: false` check to work as intended.
- K3s configuration for etcd is largely validated via yaml files, not passed arguments. Thus certain "flags" have different values when described in yaml and the check must be changed to match.
For reference, here is a piece of the …
> Fix to empty grep and other cis-1.6-k3s checks

- check/check.go
In case of RKE, env error comes with exit status 1, so added OR codition to match with error text as well.
resolve: #1364
> bugfix: false negative when audit_config file not found

- .goreleaser.yml
Resolves https://github.com/aquasecurity/kube-bench/issues/1419
Tested locally:
> add darwin builds

- cmd/util.go
- cmd/util_test.go
When we are trying to access a file from a directory which is not present then we get different error. We dont have standard error method to check the msg so added string match for this case
#1439
> fix: ignore the error from findConfigFile

- cfg/cis-1.7/node.yaml
**CIS version**: `cis-1.7`
**Target**: node.yaml
**Test id**:  `4.2.12` 
**Test text**:  Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers (Manual). 
**Test modification**: `test_items`
**Reason**: The test_items in cis-1.7 `4.2.12` does not match the test's text and remediation.
**Fix**: Used previous version test_items in `cis-1.24` of `4.2.12` (known as `4.2.13` in `1.24`)
**Related bug issue**: https://github.com/aquasecurity/kube-bench/issues/1468
> Fix test_items in cis-1.7 - node - 4.2.12

- cfg/ack-1.0/node.yaml
- cfg/cis-1.20/node.yaml
- cfg/cis-1.23/node.yaml
- cfg/cis-1.24/node.yaml
- cfg/cis-1.5/node.yaml
- cfg/cis-1.6/node.yaml
- cfg/cis-1.7/node.yaml
@mozillazg As discussed in [1467](https://github.com/aquasecurity/kube-bench/pull/1467), I am creating this PR to fix the 4.1.7 and 4.1.8 in node.yaml for the versions `cis-1.5, cis-1.6, cis-1.20, cis-1.23, cis-1.24, cis-1.7, ack-1.0`, by adding `uniq`at the end of the caudit command.
```
cfg git:(node-4.1.7-4.1.8-audit-uniq) ✗ grep -ri -A3  '4.1.7\|4.1.8' . | grep 'apiserver' -B4 | grep 'id\|apiserver' 
./cis-1.20/node.yaml:      - id: 4.1.7
./cis-1.20/node.yaml-          CAFILE=$(ps -ef | grep kubelet | grep -v apiserver | grep -- --client-ca-file= | awk -F '--client-ca-file=' '{print $2}' | awk '{print $1}' | uniq)
./cis-1.20/node.yaml:      - id: 4.1.8
./cis-1.20/node.yaml-          CAFILE=$(ps -ef | grep kubelet | grep -v apiserver | grep -- --client-ca-file= | awk -F …
```
> Fix node.yaml - 4.1.7 and 4.1.8 audit by adding uniq

- .github/workflows/publish.yml
- Dockerfile.fips.ubi
- fipsonly.go
- makefile
For fips complaince we need to generate fips compliant images. As part of this change, we will create new kube-bench image which will be fips compliant. Image name follows this tag pattern <version>-ubi-fips
> chore: add fips compliant images

- Dockerfile
- Dockerfile.ubi
During a recent CVE scan we found kube-bench to use `alpine:3.18` as the final image which has a known high CVE.
```
grype aquasec/kube-bench:v0.6.15
✔ Vulnerability DB        [no update available]
✔ Loaded image
✔ Parsed image
✔ Cataloged packages      [73 packages]
✔ Scanning image...       [4 vulnerabilities]
├── 0 critical, 4 high, 0 medium, 0 low, 0 negligible
└── 4 fixed
NAME        INSTALLED  FIXED-IN  TYPE  VULNERABILITY  SEVERITY
libcrypto3  3.1.0-r4   3.1.1-r0  apk   CVE-2023-2650  High
libssl3     3.1.0-r4   3.1.1-r0  apk   CVE-2023-2650  High
openssl     3.1.0-r4   3.1.1-r0  apk   CVE-2023-2650  High
```
The CVE in question was addressed in the latest [alpine release](https://www.alpinelinux.org/posts/Alpine-3.15.9-3.16.6-3.17.4-3.18.2-released.html), hence updating the …
> Bump docker base images

- cfg/ack-1.0/node.yaml
- cfg/cis-1.20/node.yaml
- cfg/cis-1.23/node.yaml
- cfg/cis-1.24/node.yaml
- cfg/cis-1.5/node.yaml
- cfg/cis-1.6/node.yaml
- cfg/cis-1.7/node.yaml
- cfg/cis-1.8/node.yaml
Issue: The initial command produces "root:root" as its output only when the file is present. However, if the file is missing, the command will still run successfully, though the desired output of "root:root" won't be obtained.
Fix: To address this, we've modified the command to achieve the following:
Verify the existence of the file.
If the file is found, show the user and group ownership in the "username:groupname" format.
If the file is not found, display the message "File not found."
To accommodate this change, we've integrated the expected output "File not found" for instances where the file is absent. This adjustment ensures the successful execution of the test.
>  The Kubernetes CIS reports indicate that N/A is recorded as a failure for 4.1.2 (node.yaml)

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
- go.sum
> chore: update go version to 1.21

- cfg/k3s-cis-1.23/node.yaml
- cfg/k3s-cis-1.24/node.yaml
- cfg/k3s-cis-1.7/node.yaml
- cfg/rke-cis-1.23/node.yaml
- cfg/rke-cis-1.24/node.yaml
- cfg/rke-cis-1.7/node.yaml
- cfg/rke2-cis-1.23/node.yaml
- cfg/rke2-cis-1.24/node.yaml
- cfg/rke2-cis-1.7/node.yaml
1. Have modified test criteria such that it produces right output in case of there is no file exists.
2. Have modified the tests wherever root:root is checked both in flag and value.
> Rancher node checks correction

- cfg/rke-cis-1.24/controlplane.yaml
- cfg/rke-cis-1.24/master.yaml
- cfg/rke-cis-1.24/node.yaml
- cfg/rke-cis-1.24/policies.yaml
corrected few benchmarks with title and respective tests 
Handled type and title mismatch
Added missing audit commands
> update rke-cis-1.24 benchmarks: corrected errors and tests

- cfg/rh-1.0/etcd.yaml
- cfg/rh-1.0/master.yaml
- cfg/rh-1.0/node.yaml
- cfg/rh-1.0/policies.yaml
Currently, certain commands involve retrieving all node names or pods and then executing additional commands in a loop, resulting in a time complexity linearly proportional to the number of nodes.This approach becomes time-consuming for larger clusters.
As kube-bench is executed as a job on every node in the cluster, To enhance performance, Streamlined the commands to execute directly on current node where kube-bench operates. This change ensures that the time complexity remains constant, regardless of the cluster size. By running the necessary commands only once per node, regardless of how many nodes are in the cluster, this approach significantly boosts performance and efficiency.
> perf: Improve KubeBench Performance on OCP Cluster

- .github/workflows/build.yml
- cfg/config.yaml
- cfg/k3s-cis-1.23/config.yaml
- cfg/k3s-cis-1.23/etcd.yaml
- cfg/k3s-cis-1.23/master.yaml
- cfg/k3s-cis-1.24/config.yaml
- cfg/k3s-cis-1.24/etcd.yaml
- cfg/k3s-cis-1.24/master.yaml
- cfg/k3s-cis-1.7/config.yaml
- cfg/k3s-cis-1.7/etcd.yaml
- cfg/k3s-cis-1.7/master.yaml
Background:
When https://github.com/aquasecurity/kube-bench/pull/1523 was merged, it pulled the cfg checks directly from https://github.com/rancher/security-scan/tree/master/package/cfg.
Problem:
- These checks utilizes a custom sonobuoy plugin to deploy kube-bench + [additional helper scripts](https://github.com/rancher/security-scan/tree/master/package/helper_scripts). These additional helper scripts were not accounted for when copying over the cfg. K3s utilizes kine which allows sqlite and other non etcd databases. The helper scripts allowed CIS check to pass on these other DB. These helper scripts do not exist in upstream kubebench.
Solution:
- This PR fixes the k3s 1.23, 1.24, and 1.7 benchmarks, restoring the correct etcd checks
Note: This means that running these benchmarks will …
> Replace custom k3s etcd script checks with vanilla grep checks

- .goreleaser.yml
Statically link the generated binaries as to avoid issues when the application is linked to a different GLIBC version than the one available when `kube-bench` is used.
This also removes the debug information, resulting on the assets being half the current size (`~13MB` each instead of `~25MB`).
Fixes https://github.com/aquasecurity/kube-bench/issues/1592.
> Statically link binaries and remove debug information

- cfg/rke2-cis-1.24/master.yaml
- cfg/rke2-cis-1.24/node.yaml
**MASTER**:
a. Checks **1.1.10,1.1.2**: In The case of manual checks, ideally  the user also checks if the required configuration  files are present or not. We have augmented those checks to capture that information as well, and run the actual audit only when th corresponding configuration files are found.
b. **Check 1.3.6**: is not relevant to an RKE2 cluster as RKE2 rotates TLS certificates internally - rancher/dashboard#4485. We will skip it and not score it
2. **NODE**:
a. Check 4.2.12 is the node-level equivalent of the master-level check 1.3.6 and is treated the same way.
> FIXING RKE-2-CIS-1.24 Checks

- cfg/config.yaml
- cfg/k3s-cis-1.23/controlplane.yaml
- cfg/k3s-cis-1.23/master.yaml
- cfg/k3s-cis-1.23/node.yaml
- cfg/k3s-cis-1.24/config.yaml
- cfg/k3s-cis-1.24/controlplane.yaml
- cfg/k3s-cis-1.24/etcd.yaml
- cfg/k3s-cis-1.24/master.yaml
- cfg/k3s-cis-1.24/node.yaml
- cfg/k3s-cis-1.24/policies.yaml
- cfg/k3s-cis-1.7/config.yaml
- cfg/k3s-cis-1.7/controlplane.yaml
- cfg/k3s-cis-1.7/etcd.yaml
- cfg/k3s-cis-1.7/master.yaml
- cfg/k3s-cis-1.7/node.yaml
- cfg/k3s-cis-1.7/policies.yaml
- cfg/k3s-cis-1.8/config.yaml
- cfg/k3s-cis-1.8/controlplane.yaml
- cfg/k3s-cis-1.8/etcd.yaml
- cfg/k3s-cis-1.8/master.yaml
- cfg/k3s-cis-1.8/node.yaml
- cfg/k3s-cis-1.8/policies.yaml
- cfg/rke-cis-1.23/policies.yaml
- cfg/rke-cis-1.24/policies.yaml
- cfg/rke-cis-1.7/policies.yaml
- An effort to overhaul the K3s and RKE2 scans is being undertaken in the [rancher/security-scan](https://github.com/rancher/security-scan) repo. These changes are being upstreamed into the kube-bench project. 
- This is a combination of the following PRs:
- https://github.com/rancher/security-scan/pull/221
- https://github.com/rancher/security-scan/pull/219
- https://github.com/rancher/security-scan/pull/228
- https://github.com/rancher/security-scan/pull/232
- Overhaul existing K3s v1.24 and v1.7 scans, ensuring that
- All checks have proper remeditation sections that give specific details on K3s, not just the general CIS scans
- All checks use the `Automated` and `Manual` correctly, identifiying what K3s by default will handle, and when user action in needed.
- All checks have proper …
> Overhaul of K3s scans

- go.mod
This PR adds support for [Go Toolchains](https://go.dev/doc/toolchain).
There is a PR (ex. https://github.com/aquasecurity/kube-bench/pull/1681), that can't be merged without a specific go toolchain.
so to keep up to date  the dependencies we should indicate go toolchain.
also I fixed some vulnerabilities.
Before:
```sh
$ go build -o my-kb .
$ trivy rootfs .
2024-10-24T12:28:39+06:00	INFO	[vuln] Vulnerability scanning is enabled
2024-10-24T12:28:39+06:00	INFO	[secret] Secret scanning is enabled
2024-10-24T12:28:39+06:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-10-24T12:28:39+06:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.56/docs/scanner/secret#recommendation for faster secret detection …
```
> chore: add go toolchain version

- cfg/cis-1.24/master.yaml
If `--bind-address` of kube-scheduler and kube-controller-manager is not set it defaults to 0.0.0.0 (all interfaces) [1, 2].
The respective checks (1.3.7 and 1.4.2) should not accept the default bind-address value and should fail if `--bind-address` is not set.
[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
[2] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
> Ensure 127.0.0.1 for the --bind-address parameter

- cfg/rke-cis-1.7/master.yaml
- cfg/rke-cis-1.7/node.yaml
This PR changes the folder name for certificate files in rke-cis-1.7.
fixes #1746
> fix: change the folder name for certificate files in rke-cis-1.7

- .goreleaser.yml
This PR solves https://github.com/aquasecurity/kube-bench/discussions/1767 by compiling against the build directory instead of `main.go`. This will add the proper package path inside the binary and allow VEX entries to be matched against the kube-bench binary.
```
> go version -m dist/kube-bench | head -n 3
dist/kube-bench: go1.23.4
path	github.com/aquasecurity/kube-bench
mod	github.com/aquasecurity/kube-bench	(devel)	
```
> VEX related improvements in the build process

- go.mod
- go.sum
An attacker can craft an input to the Parse functions that would be processed non-linearly with respect to its length, resulting in extremely slow parsing. This could cause a denial of service.
https://avd.aquasec.com/nvd/2024/cve-2024-45338/
> fix: CVE-2024-45338[CRITICAL]: Inefficient Regular Expression Complexity

- Dockerfile
- Dockerfile.fips.ubi
- Dockerfile.ubi
in #1781 there were missed args in result images for labels in Dockerfiles.
this PR adds args for alpine based images.
```sh
$ make build-docker
$ docker inspect aquasec/kube-bench:5557601 | grep label
```
Before:
```sh
"org.label-schema.build-date": "2025-01-21T06:29:34Z",
"org.label-schema.description": "Run the CIS Kubernetes Benchmark tests",
"org.label-schema.maintainer": "admin@aquasec.com",
"org.label-schema.name": "kube-bench",
"org.label-schema.release": "",
"org.label-schema.schema-version": "1.0",
"org.label-schema.summary": "Aqua security server",
"org.label-schema.url": "https://github.com/aquasecurity/kube-bench",
"org.label-schema.vcs-ref": "5557601",
"org.label-schema.vcs-url": "https://github.com/aquasecurity/kube-bench",
"org.label-schema.vendor": "Aqua Security Software …
```
> fix(ci): add missed args for building docker images

- Dockerfile
- Dockerfile.fips.ubi
- Dockerfile.ubi
- go.mod
This is the scan result of Trivy.
```
usr/local/bin/kube-bench (gobinary)
===================================
Total: 1 (UNKNOWN: 1, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬──────────────────────────────┬────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │        Fixed Version         │                   Title                    │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼──────────────────────────────┼────────────────────────────────────────────┤
│ stdlib  │ CVE-2025-22866 │ UNKNOWN  │ fixed  │ 1.23.5            │ 1.22.12, 1.23.6, 1.24.0-rc.3 │ Timing sidechannel for P-256 on ppc64le in │
│         │                │          │ …
```
> Bump golang from 1.23.5 to 1.23.6 to fix CVE-2025-22866

- docs/installation.md
The documentation used 0.6.2, a version that doesn't even install... This is a quick fix that uses a currently latest working version (0.10.1). It also combines all version references into a var. Beautify to your liking.
TODO: automate the version in release pipeline.
> Doc bugfix. Updated version in installation documentation and using a version var

- .github/workflows/build.yml
- .github/workflows/release.yml
Kube-bench already uses Go v1.23.6, so the pipeline should use the same version for tests.
> ci: bump up Go version to 1.23.6 in Github workflows

- makefile
kubectl has vulnerabilities in the stable version, it was fixed in `1.33.0-alpha.1` (https://github.com/kubernetes/kubectl/tree/v0.33.0-alpha.1).
before:
```sh
$ trivy i aquasec/kube-bench:v0.10.1 --severity HIGHaquasec/kube-bench:v0.10.1 
(alpine 3.21.2)Total: 0 (HIGH: 0)
usr/local/bin/kubectl (gobinary)Total: 2 (HIGH: 2)
┌──────────────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
├──────────────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
│ …
```
> fix: suppress vulnerabilities in kubectl

- cfg/ack-1.0/policies.yaml
- cfg/cis-1.10/policies.yaml
- cfg/cis-1.20/policies.yaml
- cfg/cis-1.23/policies.yaml
- cfg/cis-1.24/policies.yaml
- cfg/cis-1.5/policies.yaml
- cfg/cis-1.6/policies.yaml
- cfg/cis-1.7/policies.yaml
- cfg/cis-1.8/policies.yaml
- cfg/cis-1.9/policies.yaml
- cfg/k3s-cis-1.23/policies.yaml
- cfg/rh-1.0/policies.yaml
- cfg/rke-cis-1.23/policies.yaml
- cfg/rke-cis-1.24/policies.yaml
- cfg/rke-cis-1.7/policies.yaml
- cfg/rke2-cis-1.23/policies.yaml
- cfg/rke2-cis-1.24/policies.yaml
- cfg/rke2-cis-1.7/policies.yaml
- cfg/tkgi-1.2.53/policies.yaml
- integration/testdata/Expected_output.data
This PR fixes a simple typo of "applicaions" to "applications" in all files within this repo.
> Fix typo of applicaions which should have been applications

- cmd/util.go
This commit adds a default case to the switch statements for both "rancher" and "rke2" platforms. This ensures that a fallback CIS benchmark version ("rke-cis-1.7" and "rke2-cis-1.7" respectively) is returned when the Kubernetes version does not match any of the explicitly defined cases.
> fix: Add default case to RKE CIS benchmark version selection

- cfg/config.yaml
- cfg/rke2-cis-1.23/master.yaml
- cfg/rke2-cis-1.24/master.yaml
- cfg/rke2-cis-1.7/master.yaml
Resolves #1843.
This PR adds pathes to `schedulerkubeconfig` and `controllermanagerkubeconfig` to fix the failures. And replace hard coded values with variables.
> 1.1.15, 1.1.17 of `rke2-cis-1.7` fails

- job-tkgi.yaml
Running kube-bench on TKGI with the provided job template will fail with errors like:
`14:55:43.616764 3064074 check.go:190] failed to run: "grep  ^tlsCertFile:\\s\\\"\\/var\\/vcap\\/jobs\\/kubelet\\/config\\/kubelet\\.pem\\\"\\ntlsPrivateKeyFile:\\s\\\"\\/var\\/vcap\\/jobs\\/kubelet\\/config\\/kubelet-key\\.pem\\\"$\n/var/vcap/jobs/kubelet/config/kubeletconfig.yml", output: "/bin/sh: /var/vcap/jobs/kubelet/config/kubeletconfig.yml: not found\n", error: exit status 127`
This is due to the fact that /var/vcap/jobs/<subdir> only contains symbolic links to /var/vcap/data/jobs/<subdir>/<uuid>
To actually read - for example - the kubeletconfig.yml the /var/vcap/data/jobs directory needs to be mounted aswell.
Likewise /var/vcap/sys is a symlink pointing to /var/vcap/data/sys
> add necessary mounts for /var/vcap/data/jobs & sys

- .github/workflows/build.yml
This PR bumps up  golangci-lint version to v1.64 to fix unexpected linter errors:
* https://github.com/aquasecurity/kube-bench/actions/runs/14180473461?pr=1848
* https://github.com/aquasecurity/kube-bench/actions/runs/14180461348/job/39725198642?pr=1847
> chore(ci): bump up golangci-lint version to v1.64

- go.mod
this PR fixes some vulnerabilities in Go stdlib.
Before:
```sh
Report Summary
┌────────┬──────────┬─────────────────┬─────────┐
│ Target │   Type   │ Vulnerabilities │ Secrets │
├────────┼──────────┼─────────────────┼─────────┤
│ kb     │ gobinary │        3        │    -    │
└────────┴──────────┴─────────────────┴─────────┘
Legend:
- '-': Not scanned
- '0': Clean (no security findings detected)
kb (gobinary)
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬──────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                            Title                             │ …
```
> chore: bunp up Go version to 1.24.4

- makefile
This PR uses kubectl 1.34.0-alpha.1 to fix known vulnerabilities in Go stdlib.
Before:
```sh
Report Summary
┌──────────────────────────────────────────────────────┬──────────┬─────────────────┬─────────┐
│                        Target                        │   Type   │ Vulnerabilities │ Secrets │
├──────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ docker.io/aquasec/kube-bench:98aa7bb (alpine 3.22.0) │  alpine  │        0        │    -    │
├──────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ usr/local/bin/kube-bench                             │ gobinary │        0        │    -    │
├──────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ …
```
> chore: use kubectl 1.34.0-alpha.1
