aquasecurity/kube-bench

cmd/common.go, cmd/root.go
=> If output format is JSON, don't also output human-readable warnings 

cfg/config.yaml, cfg/federated.yaml, cfg/master.yaml, cfg/node.yaml, check/check.go, check/controls.go, cmd/common.go, cmd/root.go, cmd/util.go, main.go
Support --installation option. Currently supports kops, hyperkube, kubeadm and the default installation. Will need some fleshing out for the bin/conf paths (#17).
Also added a --verbose flag to print verbose messages for debugging (#16).
=> Issues #17, #16

cfg/config.yaml, check/check.go, check/controls.go, cmd/common.go, cmd/root.go, cmd/util.go
Check out what I have been working on for error handling:
1. added support for glog log levels: 
$ kube-bench master
$ kube-bench master -v 1
$ kube-bench master -v 2  # can get very loud
1. Error handling is now at call site, no longer propagating errors.
=> Improve error handling.

cfg/master.yaml, cfg/node.yaml, check/check.go
Reverts aquasecurity/kube-bench#30 - sorting out bad merge
=> Revert "Issue 19"

cfg/master.yaml, cfg/node.yaml, check/check.go
=> Issue 19, take 2

check/test.go
Fixed issue of The controls for master - admission control showing wrong status #49
Changed the regex
=> Fixed issue admission control showing wrong status

cfg/1.6/federated.yaml, cfg/1.6/master.yaml, cfg/1.6/node.yaml, cfg/1.7/federated.yaml, cfg/1.7/master.yaml, cfg/1.7/node.yaml, check/controls.go, check/controls_test.go, cmd/common.go, cmd/federated.go, cmd/master.go, cmd/node.go, cmd/util.go, cmd/util_test.go
This PR is supposed to be a cleaned up version of [PR#46](https://github.com/aquasecurity/kube-bench/pull/46).
Some questions on that PR apply here.
To keep this clean I did not merge kube-bench HEAD.
=> Support multiple kubernetes version

cfg/1.8/federated.yaml, cfg/1.8/master.yaml, cfg/1.8/node.yaml, cfg/config.yaml, cmd/common.go, cmd/util.go, cmd/util_test.go
=> Add kubernetes 1.8 support

check/controls.go, cmd/common.go, cmd/database.go, cmd/root.go, makefile
majority of changes in savePgsql() in common.go
=> added saving results to PostgreSQL DB as a JSONB document

cmd/common.go, cmd/root.go, cmd/util.go, cmd/util_test.go
=> Exit kube-bench if we can't get valid kubernetes server version

check/check.go, check/controls.go
Changes to the json structure and field names
=> Result structure changes

.gitignore, README.md, glide.lock, glide.yaml
Add glide dependencies.
Fixes #79
=> Add glide dependencies

cfg/1.8/config.yaml, cfg/1.8/master.yaml, cfg/1.8/node.yaml, cfg/config.yaml, cmd/common.go, cmd/util.go, cmd/util_test.go
=> Remove unnecessary warnings about missing config files.

.goreleaser.yml
Remove docker builds from goreleaser as per discussion in #80
=> Remove docker build

cmd/common.go, cmd/database.go, cmd/root.go, cmd/util.go
Once the travis updates in #83 are merged, I'll update to have vet and lint working
=> Lint all code for golint tests

cfg/1.8/master.yaml
I found a few very small bugs in the 1.8 configuration
=> Test fixes for 1.8

cmd/common.go, cmd/util.go
Try to use kubelet when kubectl is unavailable
Resole #97
=> Use kubelet

cmd/common.go
=> Use 1.8 tests for k8s 1.9 and 1.10

.goreleaser.yml
https://goreleaser.com/#deprecation_notices.fpm
=> Update to nfpm as fpm is deprecated

cfg/1.8/config.yaml, cmd/common.go, cmd/util.go, cmd/util_test.go
As per discussion in #136. 
Oops, I have left the config file changes in this branch for the .manifest extension support. Never mind, hopefully it will merge OK.
=> Default version 

cmd/common.go, cmd/util.go
=> Shouldn't need kubelet or kubectl if version specified

check/check.go, check/controls.go, check/data, check/test.go, check/test_test.go
This PR adds the actual value of the result to the json output during CIS scan.
=> Support actual result in json output.

README.md, cfg/1.11/config.yaml, cfg/1.11/master.yaml, cfg/1.11/node.yaml
=> Update tests for Kubernetes 1.11

cfg/1.11/master.yaml
Correcting the logic of 1.1.14 for Kubernetes 1.11.
=> Fixes https://github.com/aquasecurity/kube-bench/issues/170

README.md, job-master.yaml, job-node.yaml
See #197 
@ttousai as well as reviewing this please could you test it on a multi-node cluster to confirm whether the nodeSelector and tolerations are correct?
=> For #197 - create job YAML files that mount host volumes as needed

cfg/ocp-3.10/config.yaml, cfg/ocp-3.10/federated.yaml, cfg/ocp-3.10/master.yaml, cfg/ocp-3.10/node.yaml, check/check.go, check/controls.go, check/test.go, cmd/common.go
A place to collect commits for OCP benchmark work.
=> OCP benchmarks and configs

cfg/config.yaml, cfg/ocp-3.10/config.yaml
=> Update openshift executable config

README.md
Also describe how tests can be omitted by editing the YAML
=> Document output states

cmd/common.go, cmd/root.go
=> Printing the actual test result of failed tests - when a flag is raised

cfg/ocp-3.10/config.yaml
As recommended by @bgoareguer in https://github.com/aquasecurity/kube-bench/issues/242#issuecomment-494722911
=> Update openshift executables

docs/README.md
This PR documents kube-bench configuration and benchmark specification.
=> Rationalize and document config

cfg/config.yaml
Added another path to search in, In the main config yaml:
*/home/kubernetes/kubelet-config.yaml*
This is a default location found in a GKE cluster
=> Added another kubelet config file to node:kubelet:confs

README.md
Provide a guide to our users on creating issues for the maintainers, and the basic information to add to reduce the time it takes to resolve issues.
=> Add github issue creation instructions.

README.md
Use the GitHub terminology since draft PRs are a thing
=> docs: update WIP to draft

cmd/util.go
Adding a comment in case this rather [obscure limitation of procps](https://github.com/aquasecurity/kube-bench/issues/328#issuecomment-506813344) comes up again
=> Add comment about procps limitation

cfg/1.13-json/config.yaml, cfg/1.13-json/node.yaml
Adds the JSON configuration files used when executing kube-bench on EKS.
=> issue #323: Add json version of config for k8s 1.13

cfg/1.11-json/node.yaml, cfg/1.11/node.yaml, cfg/1.13/node.yaml, cfg/1.8/node.yaml, cfg/config.yaml, cmd/common.go, cmd/util.go
implement test 2.2.8 for the resolution of issue #234
=> issue #234: implement test 2.2.8

cfg/1.13-json/node.yaml, cfg/1.13/node.yaml
Changed substitution variable (kubeletconf -> kubeletsvc).
=> Issue #345: Changed substitution variable (kubeletconf -> kubeletsvc).

cfg/1.13-json/node.yaml
Applies changes made in PR #343.
=> issue #349: changes test 2.2.8

check/test.go, check/test_test.go
Adds Unit Tests for JSONPath Parse & Execute.
=> Issue #355: Adds Unit Tests for JSONPath Parse & Execute

.goreleaser.yml
=> Remove Darwin build from go-releaser

cmd/common.go, cmd/util.go, cmd/util_test.go
* issue #348: replace everywhere get(Thing)Files with getFiles
=> Issue #348: Refactor get<Thing>Files into getFiles

check/check.go
Changes condition so that score: false tests are performed.
=> issue #243: Changes condition so that score: false tests are performed

check/test.go, check/test_test.go
- Extracted the compare operations into a function called `compareOp`
- Added a set of Unit Tests
=> Issue #363: Adds Unit Tests for Test Comparisons

cfg/1.13-json/node.yaml
Fixes RotateKubeletServerCertificate tests in 1.13-json
=> issue #369: fixes RotateKubeletServerCertificate tests in 1.13-json

cfg/1.11-json/node.yaml, cfg/1.13-json/node.yaml
Fixes issue #346 by explicitly only checking read-only property
=> Fixes issue #346 by explicitly only checking read-only property

README.md
Strictly, we don't have the changes in 1.13-json but we do have them in 1.13. 
Relates to #370
=> Updated version support

cfg/1.13/master.yaml
=> Correct 1.1.13 to match CIS spec

cfg/1.11-json/node.yaml, cfg/1.11/node.yaml, cfg/1.13-json/node.yaml, cfg/1.13/node.yaml
Fixes issue #396   
Replaces `$kubeletconf ` for `$kubeletsvc `
=> Fixes Issue #396 - Replaces $kubeletconf for $kubeletsvc

cfg/1.11-json/node.yaml, cfg/1.13-json/node.yaml
Fixes issue #407.
I'm open to any changes.
=> Fixes issue #407

cfg/1.11-json/node.yaml, cfg/1.11/node.yaml, cfg/1.13/node.yaml
Fixes issue #243 
Changes to use the **"op: valid_elements"** operation to manage a list of items.
=> Fixes issue #243: Using "op: valid_elements"

makefile
Something with the old version was crashing. now using the most recent one 1.15.3 is working.
=> Change Kind version

check/test.go, check/test_test.go
Fixes issue #364
Adds Unit Tests for check/toNumeric
=> Adds Unit Tests for check/toNumeric

Dockerfile, makefile
Fixes issue #391: passes KUBEBENCH_VERSION down to Dockerfile
=> Fixes issue #391: passes KUBEBENCH_VERSION down to Dockerfile

CONTRIBUTING.md
=> Fix typo in Contributing file

cfg/config.yaml, cfg/rh-0.7/config.yaml, cfg/rh-0.7/node.yaml
=> Openshift configs

.goreleaser.yml, cmd/root.go
=> Fixes issue #536

Dockerfile, cfg/config.yaml, cfg/node_only.yaml, cfg/rh-0.7/config.yaml, cmd/common.go, cmd/common_test.go, cmd/root.go
Fixes Issue #535
- Changes isEtcd condition so it only executes for CIS tests and not OpenShift tests.
- Adds `openssl`
- Adds programs for OpenShift OKD when installed using Minishift.
=> Fixes Issue #535

hooks/build
For some reason GitHub wouldn't do this merge for PR #496 automatically
=> Complete merge for #496

cfg/cis-1.3/master.yaml, cfg/cis-1.4/master.yaml, integration/testdata/job-master.data, integration/testdata/job.data
addresses:
- https://github.com/aquasecurity/kube-bench/issues/542
- https://github.com/aquasecurity/kube-bench/issues/543
=> fix mismatching checks

integration/integration.go, integration/integration_test.go
Fixes issues #552
Improves performance and reliability.
=> Integration Test: Improves performance and Reliability

integration/integration_test.go
Integration tests:  Fixes #559
Adds `generateDiff` function to make it easier to see the difference between expected output and result.
Here is a sample output:
```console
--- FAIL: TestRunWithKind (160.86s)
--- FAIL: TestRunWithKind/kube-bench (9.12s)
integration_test.go:77: expected results
Expected    (<)
Result      (>)
line: 25
< [PASSa] 1.1.23 Ensure that the --service-account-lookup argument is set to true (Scored)
> [PASS] 1.1.23 Ensure that the --service-account-lookup argument is set to true (Scored)
line: 31
< [bFAIL] 1.1.29 Ensure that the --client-ca-file argument is set as appropriate (Scored)
> [FAIL] 1.1.29 Ensure that the --client-ca-file argument is set as appropriate (Scored)
line: 516
< 1 checks INFO2
< 1 checks INFO3
> [[NO MORE DATA]]
--- PASS: …
```
=> Integration Tests: Adds generateDiff Function

cfg/cis-1.4/master.yaml, cfg/cis-1.5/master.yaml, integration/testdata/job-master.data, integration/testdata/job.data
=> Change to checking `--disable-admission-plugins` for cis-1.4-1.1.27 and cis-1.5-1.2.14

cfg/cis-1.5/node.yaml
proykubeconfig -> proxykubeconfig
=> fix small typo

check/data, check/test.go, check/test_test.go
=> Support parse boolean flag with no value

cfg/cis-1.3/master.yaml, cfg/cis-1.4/master.yaml, cfg/config.yaml, cfg/node_only.yaml
=> Support config files which use .yml file extension

README.md
Also adds links to the Kubernetes benchmarks
Fixes #596
=> Add GKE into list of support tests

cfg/config.yaml
For running my own experiments I have added config paths for [Canonical's MicroK8s](https://github.com/ubuntu/microk8s). What do you think? Would it make sense to merge these to upstream?
=> Add config paths for microk8s

Dockerfile
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
=> bumped to gloang 1.14.0

README.md
Added a Please Note section to document common misunderstandings that often lead to incorrect issue filings
=> docs: notes in README for common misunderstandings

cfg/cis-1.3/node.yaml, cfg/cis-1.4/node.yaml, cfg/cis-1.5/node.yaml
Fixes #598
Ref #634
Test
Before:
After:
=> Try to search the right ca file of kubelet

README.md
Adding basic instructions for running with debug logs. 
Also, while I'm editing this file, adding note to address #613
=> docs: add Troubleshooting

Dockerfile
https://alpinelinux.org/posts/Alpine-3.12.0-released.html
=> Dockerfile: Update to alpine-3.12

cfg/cis-1.5/node.yaml, integration/testdata/cis-1.5/job-node.data, integration/testdata/cis-1.5/job.data
=> 4.1.7 of cis-1.5 should not be marked as manual

cfg/cis-1.5/master.yaml
=> Check PodSecurityPolicy when test 1.2.13 of cis-1.5

check/test.go
Refactor testitem-set to be default true https://github.com/aquasecurity/kube-bench/issues/658
=> Refactor testitem-set

README.md, cfg/cis-1.5/master.yaml, cfg/cis-1.5/node.yaml, cfg/cis-1.5/policies.yaml, integration/testdata/cis-1.5/job-master.data, integration/testdata/cis-1.5/job-node.data, integration/testdata/cis-1.5/job.data
=> Support CIS v1.5.1

cfg/cis-1.5/master.yaml
=> Add a trailing slash to find directory path

README.md
=> docs: more clarification on output states

Dockerfile
Upgrade golang base image to 1.15
=> upgrade to go version 1.15

cfg/cis-1.6/master.yaml, integration/testdata/cis-1.6/job-master.data, integration/testdata/cis-1.6/job.data
=> Fix typo of 1.1.19 in cis-1.6

cfg/aks-1.0/config.yaml, cfg/aks-1.0/controlplane.yaml, cfg/aks-1.0/managedservices.yaml, cfg/aks-1.0/master.yaml, cfg/aks-1.0/node.yaml, cfg/aks-1.0/policies.yaml, cfg/config.yaml, cmd/common_test.go
Created config and test files for Azure Kubernetes Service. Config and test files are found in new aks-1.0 folder.
Control plane, managed services, and policies config and tests are based on Microsoft's AKS best practices documentation.
Node config and tests are based on CIS-1.6 benchmark.
=> Created config and test files for Azure Kubernetes Service (AKS).

cfg/cis-1.5/master.yaml, cfg/cis-1.5/node.yaml, cfg/cis-1.6/master.yaml, cfg/cis-1.6/node.yaml, integration/testdata/cis-1.5/job-master.data, integration/testdata/cis-1.5/job-node.data, integration/testdata/cis-1.5/job.data, integration/testdata/cis-1.6/job-master.data, integration/testdata/cis-1.6/job-node.data, integration/testdata/cis-1.6/job.data
Closes https://github.com/aquasecurity/kube-bench/issues/743
* https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
* https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
* https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
=> Pass RotateKubeletServerCertificate related checks if it's not found

check/controls.go, cmd/common.go, cmd/common_test.go, cmd/root.go, cmd/testdata/result.json, cmd/testdata/result_no_totals.json, cmd/util.go, go.mod, integration/testdata/cis-1.5/job-master.data, integration/testdata/cis-1.5/job-node.data, integration/testdata/cis-1.5/job.data, integration/testdata/cis-1.6/job-master.data, integration/testdata/cis-1.6/job-node.data, integration/testdata/cis-1.6/job.data
Whether the total summary is shown can be specified with an option.
Fixes #528
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
=> Add a total summary and always show all tests.

LICENSE, README.md
=> Update Readme.md file with link to Contribution guide

.github/workflows/publish.yml
So we can trigger publish manually
=> Add manual workflow dispatch to Publish

cfg/config.yaml
=> add new proxy path

.github/workflows/build.yml, .github/workflows/release.yml
=> chore: fix YAML lint errors

cmd/master.go, cmd/node.go, job-master.yaml, job-node.yaml
=> deprecate master and node subcommands

cmd/kubernetes_version.go, cmd/kubernetes_version_test.go, cmd/util.go
issue #816  add more logging for better debug and information about version auto-detection and fix typo
=> Add version logging

Dockerfile
=> upgrade base image versions in Dockerfile

cfg/cis-1.5/policies.yaml, cfg/cis-1.6/policies.yaml, cfg/gke-1.0/policies.yaml, check/check.go, check/test.go, integration/testdata/cis-1.5/job.data, integration/testdata/cis-1.6/job.data
Some old logging was a bit misleading and lacking in information so I changed some and mostly add more logs, 
Also now the checks logs has the check ID so it much more clear what log belong to which test. 
In the image you can see how a test log looks like now:
And this is before:
=> Add logging

cfg/gke-1.0/managedservices.yaml
Update text to match CIS GKE Benchmark v1 description
=> Fix for GKE 6.5.5 Incorrect Text #854

cfg/config.yaml
Missing config.yaml mapping section for rh-1.0
=> Fix mapping version 

cfg/ack-1.0/master.yaml, cfg/cis-1.5/master.yaml, cfg/cis-1.6/master.yaml, integration/testdata/cis-1.5/job-master.data, integration/testdata/cis-1.5/job.data, integration/testdata/cis-1.6/job-master.data, integration/testdata/cis-1.6/job.data
=> Fix test request timeout

.goreleaser.yml
Issue #840 missing 'Maintainer' field in package
=> Fix issue with missing 'Maintainer' field

cfg/cis-1.6/master.yaml
=> Fix issue tests 1.1.9 and 1.1.10

cmd/common.go
=> Fix Malformed JUnit Output

docs/installation.md
- Added to the `Installing from sources`
- Includes `git clone` etc.
- Also includes comments
Fixes #856 
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>
=> doc(install): Adding detail and example for build

job-ack.yaml, job-aks.yaml, job-eks-asff.yaml, job-eks.yaml, job-gke.yaml, job-iks.yaml, job-master.yaml, job-node.yaml
Hello,
* Updates the `job-*.yamls` for consistency purposes and updated to use  `run --targets` as the prior statements in-use have been deprecated.
Thank you for Kube-bench.
=> K8s Job Command Clean

.github/workflows/release.yml
=> Remove make integration-testing

.github/workflows/build.yml, .gitignore, integration/testdata/Expected_output.data, makefile
Fix issues:
* the integration test does not build the docker image with the latest code
* can't run integration test on develop envviroment
=> Fix integration test not testing latest code and can't run test on local

cfg/cis-1.20/master.yaml, integration/testdata/Expected_output.data
https://workbench.cisecurity.org/sections/665102/recommendations/1090253
=> Fix status of cis-1.20 1.2.25 should be Manual

cfg/config.yaml
=> Add various paths as used by Talos

cfg/cis-1.20/node.yaml, integration/testdata/Expected_output.data
https://workbench.cisecurity.org/sections/665099/recommendations/1090201
=> Fix status of cis-1.20 4.1.6 should be Automated

cmd/util_test.go
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Correct typo

docs/asff.md
On this PR:
* Fix the image path for `asff` docs page.
=> Fix docs asff image

index.html
Make https://aquasecurity.github.io/kube-bench redirect to the latest docs page
=> Set default version of docs to latest

cmd/root.go, docs/flags-and-commands.md
=> Update docs about the --outputfile flag

cfg/aks-1.0/policies.yaml, cfg/eks-1.0.1/policies.yaml, cfg/gke-1.0/policies.yaml, cfg/gke-1.2.0/policies.yaml
=> Fixed typo in policies.yaml

.gitignore, job.yaml
=> release: prepare v0.6.7-rc1

job.yaml
=> release: v0.6.7

.github/workflows/build.yml, .github/workflows/release.yml
https://github.com/goreleaser/goreleaser/releases
=> Upgrade goreleaser to v1.7.0

cfg/cis-1.23/config.yaml, cfg/cis-1.23/controlplane.yaml, cfg/cis-1.23/etcd.yaml, cfg/cis-1.23/master.yaml, cfg/cis-1.23/node.yaml, cfg/cis-1.23/policies.yaml, cfg/config.yaml, cmd/common_test.go, docs/architecture.md, docs/platforms.md
=> Add support to CIS-1.23 1.0.0

job.yaml
=> release: prepare v0.6.8-rc1

job.yaml
=> release: prepare v0.6.8

check/controls.go
=> ASFF: add cluster arn to the finding ID

cmd/common.go
=> use log instead of print

check/controls.go, job-eks-asff.yaml
https://github.com/aquasecurity/kube-bench/issues/1179#issuecomment-1141566485
Fixes #1190
=> ASFF: add node name to the finding id

cfg/cis-1.20/node.yaml, integration/testdata/Expected_output.data
=> fix 4.2.11 in cis-1.20 should be `Automated`

cfg/rh-1.0/node.yaml
Removing colon from these checks so that grep command will work with both communication method (YAML and JSON)
=> Updating checks 4.2.1 and 4.2.3

job.yaml
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
=> release: prepare v0.6.9

Dockerfile
=> chore: replace gclib alpine pkg

docs/flags-and-commands.md
Small improvement to Automated/Manual documentation in response to #1282
=> docs: Improve Automated/Manual documentation

docs/flags-and-commands.md
=> docs: document --unscored flag

job.yaml
=> release: v0.6.10

cfg/cis-1.20/master.yaml, cfg/cis-1.23/master.yaml, cfg/cis-1.24/master.yaml
https://github.com/aquasecurity/kube-bench/pull/1330
=> use $etcddatadir in more etcd related checks

job.yaml
=> release: prepare  v0.6.11

job.yaml
=> release: prepare v0.6.12-rc

job.yaml
=> release: prepare v0.6.12

docs/running.md
Thanks for the awesome project!
=> docs: Clarify how to run Job on OpenShift

.github/workflows/build.yml, .github/workflows/mkdocs-deploy.yaml, .github/workflows/publish.yml, .github/workflows/release.yml, Dockerfile, Dockerfile.ubi, makefile
- added publish step to publish ubi image
- updated base image for alpine based dockerfile
=> chore: publish ubi based image

cfg/cis-1.24/policies.yaml
This PR fixes the version in cis-1.24 policies.yaml. Earlier it was cis-1.25
=> Fix version in policies.yaml

job.yaml
=> release: prepare v0.6.13-rc

job.yaml
=> release: prepare v0.6.13-rc2

job.yaml
=> release: prepare v0.6.13

check/test.go, cmd/util.go
From the closed PR  #1310
@chen-keinan
=> replace with constant string

job.yaml
=> release: prepare v0.6.14

cfg/cis-1.24/master.yaml, cfg/cis-1.24/node.yaml
=>  cis-1.24: fix tests of 1.1.1 and 4.2.9 were wrong

cfg/cis-1.7/config.yaml, cfg/cis-1.7/controlplane.yaml, cfg/cis-1.7/etcd.yaml, cfg/cis-1.7/master.yaml, cfg/cis-1.7/node.yaml, cfg/cis-1.7/policies.yaml, cfg/config.yaml, cmd/common_test.go, docs/architecture.md, docs/platforms.md
=> support CIS Kubernetes Benchmark v1.7.0

job.yaml
release: prepare v0.6.16 official
=> release: prepare v0.6.16 official

job.yaml
=> release: prepare v0.6.17

job.yaml
=> release: prepare v0.6.18

job.yaml
=> release: prepare-0.6.19

job.yaml
=> release: prepare v0.7.0

job.yaml
=> release: prepare v0.7.1

job.yaml
=> release: prepare v0.7.2

job.yaml
=> release: prepare-v0.7.3

job.yaml
=> release: prepare v0.8.0

cfg/cis-1.9/master.yaml
Parent:
-  https://github.com/aquasecurity/kube-bench/issues/1644
=> Fix audit and remediation for CIS-1.9 master 1.1.13/1.1.14

job.yaml
=> release: prepare v0.9.1

job.yaml
=> release: prepare v0.9.2

job.yaml
=> release: prepare v0.9.3

job.yaml
=> release: prepare v0.9.4

job.yaml
=> release: prepare v0.10.0

job.yaml
=> release: prepare v0.10.1

job.yaml
=> release: prepare v0.10.2

job.yaml
=> release: prepare v0.10.6

job.yaml
=> release: Prepare v0.10.7

job.yaml
=> release: prepare v0.11.1

job.yaml
=> release: prepare v0.11.2 
